// <auto-generated />
using System;
using Graph.Repositories.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Graph.Repositories.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191123154158_InitialDbCreate")]
    partial class InitialDbCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Graph.EntityModels.GraphChart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ChartDate")
                        .HasColumnName("ChartDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("MarketPrice")
                        .HasColumnName("MarketPrice")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("GraphCharts");
                });
#pragma warning restore 612, 618
        }
    }
}
